services:
  - type: web
    name: emotion-detection
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: OPENCV_VIDEOIO_PRIORITY_V4L2: 0